### ISSUE TITLE
Error while downloading database: No such file or directory

### ISSUE THREAD

**Issue by as-kamysh** [LaboratorioBioinformatica/vHULK#3]
Hello! Thank you very much for your tool and the detailed installation instruction. 
I have a problem with downloading the database. It seems that the website http://projetos.lbi.iq.usp.br/ where the database is located is down. Could you please check it and maybe add a possibility to manually download the database?
Thanks!

**Comment by lbi-usp** [comment]
Sorry for the downtime, we sometimes run into some technical difficulties. Can you please try again?

**Comment by ARossis** [comment]
Hello! i ran into the same issue. should i retry later or is there a way to manualy download the db?
Thanks
